name: coverage

on:
  push:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install nose2
      run: |
        python -m pip install --upgrade pip
        python -m pip install nose2[coverage_plugin]

    - name: Run tests with coverage
      run: nose2 -C --coverage skoolkit --coverage-report xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
