name: slow-tests

on:
  workflow_dispatch:

jobs:
  slow-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install nose2
      run: |
        python -m pip install --upgrade pip
        python -m pip install nose2

    - name: Run slow tests
      run: nose2 -c tests/slow_test.cfg
