name: z80doc-tests

on:
  workflow_dispatch:

jobs:
  z80doc-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Download z80doc.tap
      run: |
        wget https://github.com/raxoft/z80test/releases/download/v1.2/z80test-1.2.zip
        unzip -j z80test-1.2.zip z80test-1.2/z80doc.tap

    - name: Run z80doc tests
      run: |
        export SKOOLKIT_HOME=$(pwd)
        tools/z80-test-simulator.py z80doc.tap
